### ISSUE TITLE
ERROR Unknown format when trying to play `.wma` or `.ape` files

### ISSUE THREAD

**Issue by salim-b** [flathub/org.atheme.audacious#1]
I'm not quite sure if this is the right place to report this, but I have a feeling that this issue might be specifically related to the Flatpak version of Audacious.

When I try to play a `.wma` file, the following error is thrown:

```
$ flatpak run org.atheme.audacious -H ~/Musik/Marilyn-DMX.wma
ERROR ../src/ffaudio/ffaudio-core.cc:326 [open_input_file]: Unknown format for file:///home/salim/Musik/Marilyn-DMX.wma.
ERROR interface.cc:130 [aud_ui_show_error]: Fehler beim Abspielen von file:///home/salim/Musik/Marilyn-DMX.wma:
Fehler beim Lesen der Metadaten
```

When I try to play an `.ape` file, a similar error occurs:

```
$ flatpak run org.atheme.audacious -H ~/Musik/bobby.ape
ERROR ../src/ffaudio/ffaudio-core.cc:326 [open_input_file]: Unknown format for file:///home/salim/Musik/bobby.ape.
ERROR interface.cc:130 [aud_ui_show_error]: Fehler beim Abspielen von file:///home/salim/Musik/bobby.ape:
Fehler beim Lesen der Metadaten
```

(output it is partially in German; `Fehler beim Lesen der Metadaten` means "error reading metadata")

I've uploaded the `.wma` file [here](https://cldup.com/U6y6sQOS5O.wma) and the `.ape` file [here](https://cldup.com/hFVvme2zW4.ape) in case they're needed to reproduce the issues.

**Comment by tim77** [comment]
Thanks for reporting. After some investigation this turns out that this because of missing some demuxers in `.ffmpeg-full` extension. Upstream issue bug tracker:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1033

**Comment by Erick555** [comment]
@tim77 I don't see ffmpeg-full being used in [manifest](https://github.com/flathub/org.atheme.audacious/blob/master/org.atheme.audacious.yaml) so adding something there won't help you.

**Comment by tim77** [comment]
@Erick555 it's not used because no point in it at this moment until this upstream issue will be fixed. I'll add it immediately if upstream issue will be fixed or in any next Audacious update.

**Comment by Erick555** [comment]
You can create your own extension if you want: https://github.com/flathub/org.blender.Blender/pull/47

**Comment by tim77** [comment]
This is really cool. I'll look into that. Thank you @Erick555

**Comment by tim77** [comment]
@salim-b now should works with `wma` and `ape` formats, please test. But don't close this issue until this will resolved in FD runtime. Devs added milestone to `20.08` this not so long but until this we can use our own `ffmpeg` build here.

As for making it as extension: other maintainers don't recommend me doing this since removing this extension will be not so easy from Flathub itself. So this shouldn't used for such temporal solutions like our case.

**Comment by salim-b** [comment]
Awesome, thank you @tim77 ! I can confirm that both `.wma` and `.ape` files play fine now.
