### ISSUE TITLE
Plugin location

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.atheme.audacious#21]
Hey there, where is the plugin location for the flatpak build? Trying to use this plugin https://github.com/darktohka/audacious-plugin-rpc

**Comment by tim77** [comment]
Hey. If you installed `org.atheme.audacious` [user-wide](https://docs.flatpak.org/en/latest/using-flatpak.html#system-versus-user) then you should try to put it there:
```
~/.var/app/org.atheme.audacious/data/audacious/General/
```

**Comment by kurobeats** [comment]
thanks!
