### ISSUE TITLE
Audacious Pipewire output not working.

### ISSUE THREAD

**Issue by helixoid** [flathub/org.atheme.audacious#27]
With the latest update audacious is suppoosed to have pipewire audio sink but it says cannot connect to pipewire.

![Screenshot_20230306_092432](https://user-images.githubusercontent.com/110732140/223015970-6d1f43be-e7e0-41d4-acde-5f7d1c257a12.png)

**Comment by tim77** [comment]
Thanks for reporting! Please try new build which will be published soon. Please reopen the issue if problem still persist for you.
