### ISSUE TITLE
QT mode: crash when opening folder or file

### ISSUE THREAD

**Issue by KraXen72** [flathub/org.atheme.audacious#45]
when i click `open folder` or `open files` it crashes. the file picker doesen't even show up.
this happens on the flathub package version 4.4.
after running with the flatpak cli, this is the output that it gives when i try to open a folder:
```
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```
if i go to dolphin, open folder with > audacious, it works.
if i drag & drop files, it works.
it works in GTK mode, but not in QT (default) mode.
I'm using fedora 40 Kde Plasma 6.0.5
the fedora package version 4.3.1 doesen't have this issue, but it has the pipewire issue.

**Comment by tim77** [comment]
Thanks for reporting. After quick test seems like it works in QT mode for me in GNOME session. Please try upcoming build https://github.com/flathub/org.atheme.audacious/pull/46

**Comment by KraXen72** [comment]
@tim77 thanks! it's fixed in the latest build.
