### ISSUE TITLE
Drag and Drop from non-Music folder doesn't work

### ISSUE THREAD

**Issue by ramesh45345** [flathub/org.atheme.audacious#5]
I believe the current flatpak permissions don't allow for dragging and dropping songs into the playlist to work (at least from Gnome Files on the Gnome Desktop, Fedora 32 x86_64, flatpak v1.8.2).

Steps to reproduce:
1. Open the Audacious flatpak.
2. Drag an mp3 file from the home folder (or anywhere really) into the playlist.
3. Observe that the error "Error playing file:///_\<home folder\>_/test.mp3: No such file or directory" is generated.

This also manifests in such a way that when you open Audacious, and try to play the previous playlist, you will get the same error.

I compared the permissions to the VLC flatpak, where this currently works, and VLC has the "filesystems=host" permission, in addition to other miscellaneous filesystem accesses. I think this would be good to enable "filesystems=host" in the Audacious flatpak, just because music anywhere in the filesystem (not just the home folder, but in /mnt, /media, etc) could be accessed. If there are access concerns, host can be set to ro, however VLC doesn't seem to do this (likely for editing metadata and other things), so its probably fine to have it be rw.

As a workaround, this permission can be granted to the flatpak using `sudo flatpak override --filesystem=host org.atheme.audacious`, and reset/reverted to its original settings using `sudo flatpak override --reset org.atheme.audacious`. When allowing host, the above behavior/problem is fixed.

**Comment by tim77** [comment]
> Drag and Drop from Gnome Files doesn't work

Title is misleading, Drag and Drop from non-Music folder doesn't work and it shouldn't work obviously.

> --filesystem=host

God, no.
